Added Contact Section with all necessary styling
chawkimbarki/My-Portfolio pull request #10
Opened 2022-12-13 13:43 UTC by chawkimbarki

# Made changes :
- added contact section according to today's activity
-  styled according to the Figma template

2022-12-13 14:27 UTC, MaganaAsiati requested changes
# STATUS: Required Changes ♻️♻️♻️ 
## Hi @jossi30, I'm @MaganaAsiati, your reviewer for this PR  :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close-gif-4](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)

## Highlights

- Descriptive README file  :heavy_check_mark:👨🏻‍💻
- Great work using the right GitHub Flow.:heavy_check_mark:
- No Linter errors :heavy_check_mark:

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
- [ ] [OPTIONAL] Please make sure to make your commit messages more descriptive in the future. :heavy_check_mark:👨🏻‍💻
- [ ] [OPTIONAL] kindly  Add a meaningful description to your pull request in the future which gives more information about what you implement in this milestone :heavy_check_mark:👨🏻‍💻


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-12-13 14:27 UTC, MaganaAsiati commented on index.html
> +        </section>
- [ ] You did a great job in the design of your contact form it looks nice however you forget to implement the part i shows in the picture below kindly implement it as required in the project your design must stick to the Figma design as much as possible :+1: 
![image](https://user-images.githubusercontent.com/95297251/207353740-94c7472d-434f-4473-8772-4f4e50bf0890.png)

2022-12-13 14:45 UTC, chawkimbarki commented
Hello @MaganaAsiati
thanks for the detailed review, but I think that this is not a part of the contact section
<img width="158" alt="image" src="https://user-images.githubusercontent.com/77485409/207363216-932891fe-4b80-45ff-95bd-c2b4e1af8279.png">

as you can see here, they only asked us to do the contact form, not the social links part
<img width="656" alt="image" src="https://user-images.githubusercontent.com/77485409/207363730-8c10dfe6-02cf-4f17-8f4d-a4cd1586282e.png">

please if I miss understood the activity explain it to me if possible
I really appreciate it.

Thanks in advance

2022-12-15 11:04 UTC, TuyishimireEric approved these changes
# Status: APPROVED 🟢  
### Hi  @chawkimbarki     👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉 

## Highlights
✔️ Professional Pull Request 👍
✔️ No Linter errors 👍   

## Optional Requirements 
_Check the comments below_
 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-15 11:04 UTC, TuyishimireEric commented on index.html
> +                <button type="submit" id="contact-button" class="primary-button">Start Collaboration</button>
- [ ] [OPTIONAL] Kindly remember to add button interactions such as **hover, active (when it's pressed), disabled, and enable (default state)** on all your buttons as shown in the Figma template. 😂 
![image](https://user-images.githubusercontent.com/102757126/207842946-9e538412-4155-4e5b-8890-3ce209433dd0.png)

2022-12-15 11:07 UTC, merged